services:
  - type: web
    name: bgremover-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
staticSites:
  - name: bgremover-frontend
    rootDir: frontend
    publishPath: .
